"""
Django settings for hostel_gatepass project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dev-key-for-development')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.onrender.com',
    '74.220.48.0/24',
    '74.220.56.0/24',
]

if os.environ.get('ALLOWED_HOSTS'):
    ALLOWED_HOSTS.extend(os.environ.get('ALLOWED_HOSTS').split(','))

# Security settings for production
if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps for API support
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    # Local apps
    'gatepass',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hostel_gatepass.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'gatepass' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gatepass.context_processors.notifications_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'hostel_gatepass.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration - uses DATABASE_URL environment variable
database_url = os.environ.get("DATABASE_URL", f"sqlite:///{BASE_DIR}/db.sqlite3")

# For Vercel, use SQLite if no DATABASE_URL is provided
if not os.environ.get("DATABASE_URL"):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'CONN_MAX_AGE': 0,  # Disable persistent connections for SQLite
            'OPTIONS': {
                'timeout': 60,  # Increase SQLite timeout to 60 seconds for database locks
                'isolation_level': None,  # Autocommit mode
                'check_same_thread': False,  # Allow multi-threaded access
            }
        }
    }
else:
    # Update database configuration from DATABASE_URL environment variable
    DATABASES = {
        'default': dj_database_url.parse(database_url, conn_max_age=600)
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# Password validation settings
AUTH_PASSWORD_VALIDATORS = []

# Custom password validation to ensure special characters
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = [
    BASE_DIR / 'gatepass' / 'static',
]

# Media files (User uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'gatepass.User'

# Login/Logout URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# REST framework configuration (Token auth)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# during development allow CORS from mobile clients; change in production
CORS_ALLOW_ALL_ORIGINS = True

# Increase the limit for bulk operations in admin (default is 1000)
# This allows deleting many records at once without hitting the limit
# Set to a very high number to handle large bulk deletions
DATA_UPLOAD_MAX_NUMBER_FIELDS = 50000

# Database Firewall Settings
FIREWALL_RATE_LIMIT_REQUESTS = int(os.environ.get('FIREWALL_RATE_LIMIT_REQUESTS', '100'))  # requests per window
FIREWALL_RATE_LIMIT_WINDOW = int(os.environ.get('FIREWALL_RATE_LIMIT_WINDOW', '60'))  # seconds

# IP whitelisting/blacklisting
FIREWALL_WHITELIST_IPS = os.environ.get('FIREWALL_WHITELIST_IPS', '').split(',') if os.environ.get('FIREWALL_WHITELIST_IPS') else []
FIREWALL_BLACKLIST_IPS = os.environ.get('FIREWALL_BLACKLIST_IPS', '').split(',') if os.environ.get('FIREWALL_BLACKLIST_IPS') else []

# Security monitoring settings
FIREWALL_LOG_SUSPICIOUS_ACTIVITY = os.environ.get('FIREWALL_LOG_SUSPICIOUS_ACTIVITY', 'True').lower() == 'true'
FIREWALL_BLOCK_SUSPICIOUS_IPS = os.environ.get('FIREWALL_BLOCK_SUSPICIOUS_IPS', 'False').lower() == 'true'

# Email settings
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "no-reply@gmail.com")

# Email backend configuration
# Check if email credentials are provided
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
has_email_credentials = EMAIL_HOST_USER and EMAIL_HOST_PASSWORD

# Email backend configuration
# If EMAIL_BACKEND is explicitly set, use it (but still check credentials in the email function)
# Otherwise, use SMTP if credentials exist, console if not
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend" if has_email_credentials else "django.core.mail.backends.console.EmailBackend"
)

# If SMTP backend is selected but no credentials, fall back to console
if "smtp" in EMAIL_BACKEND.lower() and not has_email_credentials:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# SMTP settings (only used if EMAIL_BACKEND is set to SMTP)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True").lower() == "true"
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "False").lower() == "true"
# Timeout settings to prevent hanging connections (in seconds)
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "10"))
