# Generated by Django 4.2.7 on 2025-12-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0003_alter_security_shift_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload your photo for gatepass verification', null=True, upload_to='gatepass_photos/'),
        ),
        migrations.AlterField(
            model_name='security',
            name='shift',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Night', 'Night')], default='Morning', max_length=20),
        ),
    ]
