# Generated by Django 4.2.7 on 2026-01-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0004_gatepass_photo_alter_security_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload your photo for verification', null=True, upload_to='student_photos/'),
        ),
    ]
